version: '3'

services:

  db:
    image: postgres:latest
    container_name: postgresDBB
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=homework
    ports:
      - 5432:5432
    restart: always

  myApp:
    image: jakubpsz/homework
    container_name: homeworkApp
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/homework
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password